import type { ReactNode } from 'react'
import '../styles/globals.css'

function MyApp({ children }: { children: ReactNode }) {
  return (
  <html>
    <head>
      <title>Create Next App</title>
      {/* An empty script tag is enough to trigger this issue in Cypress */}
      <script></script>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      </head>
    <body>
      {children}
    </body>    
  </html>)
}

export default MyApp
